# Generated by Django 5.1.7 on 2025-03-29 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_subscription_stripe_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='stripe_product_id',
            new_name='stripe_id',
        ),
    ]
