# Generated by Django 5.1.7 on 2025-04-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0014_alter_subscriptionprice_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionprice',
            name='features',
            field=models.TextField(blank=True, help_text='Comma separated list of features', null=True),
        ),
    ]
