name: 1- Test Django Basic

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DJANGO_DEBUG: 0
      EMAIL_HOST_USER: 'test@test.test'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Setup Django Secret Key
        run: |
          GEN_KEY=$(openssl rand -base64 32)
          ech 'DJANGO_SECRET_KEY=$GEN_KEY' >> $GITHUB_ENV
      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Django Tests
        working-directory: ./src
        run: |
          python manage.py test
