name: 1- Test Django Basic

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      EMAIL_HOST_PASSWORD: 'test'
      DATABASE_URL: ${{ secrets.NEON_DATABASE_URL }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Setup Django Secret Key
        run: |
          GEN_KEY=$(openssl rand -base64 32)
          echo 'DJANGO_SECRET_KEY=$GEN_KEY' >> $GITHUB_ENV
      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Terminate Connections to Test Database
        run: |
          psql $DATABASE_URL -c "SELECT pg_terminate_backend(pg_stat_activity.pid) FROM pg_stat_activity WHERE pg_stat_activity.datname = 'test_saasdb' AND pid <> pg_backend_pid();"
      - name: Django Tests
        working-directory: ./src
        run: |
          python manage.py test --noinput
